CREATE LOGIN [appREST] WITH PASSWORD=N'tHOqQvhaCg8stKTpdjR+JfO6ntV7rFPW8QdiB5qxX2w='
, DEFAULT_DATABASE=[mySQLServerDB], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

CREATE USER [appREST] FOR LOGIN [appREST];

